#    # add host to group 'just_created' with variable foo=42
#    - add_host: name={{ ip_from_ec2 }} groups=just_created foo=42
#
#    # add a host with a non-standard port local to your machines
#    - add_host: name={{ new_ip }}:{{ new_port }}
#
#    # add a host alias that we reach through a tunnel
#    - add_host: hostname={{ new_ip }}
#                ansible_ssh_host={{ inventory_hostname }}
#                ansible_ssh_port={{ new_port }}

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add a new host to test group
      local_action: add_host hostname=baz groupname=test

    - name: Print test hosts - only shows initial hosts
      debug: msg="{{ groups.test|sort|join(', ') }}"
      register: result
      failed_when: result.msg != "bar, baz, foo"


