- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add a new host to test group
      local_action: add_host hostname=baz groupname=test

    - name: Print test hosts - only shows initial hosts
      debug: msg="{{ groups.test|sort|join(', ') }}"
      register: result
      failed_when: result.msg != "bar, baz, foo"


