- name: prep environment
  hosts: localhost
  gather_facts: False
  user: root
  vars:
    - srcdir: /tmp/foosrc
    - dstdir: /tmp/foodst
  tasks:
    - name: start sshd on port 2222
      shell: /usr/sbin/sshd -p 2222

    - name: cleanup source files
      shell: if [ -d "{{ srcdir }}"]; then rm -rf "{{ srcdir }}"; fi
    - name: create source files
      shell: mkdir "{{ srcdir }}"; touch "{{ srcdir }}"/file.a

    - name: cleaup dest files
      shell: rm -rf "{{ dstdir }}"*
      
#####################################


- name: basic tests
  hosts: ahost
  gather_facts: False
  vars:
    - srcdir: /tmp/foosrc
    - dstdir: /tmp/foodst
  tasks:
    # figure out who i am
    - shell: whoami
      register: who

    # /tmp/foosrc jtanner@127.0.0.2:/tmp/foodst.ahost
    - name: push locahost:x to remote:y.hostname
      synchronize: src="{{ srcdir }}" dest="{{ dstdir + '.' + inventory_hostname }}"
      register: result
    - debug: var=result
    - fail:
      when: "' /tmp/foosrc ' + who.stdout + '@127.0.0.2:/tmp/foodst.' + inventory_hostname not in result.cmd"
    - shell: if [ ! -d "{{ dstdir + '.' + inventory_hostname }}" ]; then exit 1; fi

    # jtanner@127.0.0.2:/tmp/foosrc /tmp/foodst.localhost
    - name: pull remote:x to remote:y.localhost
      synchronize: src="{{ srcdir }}" dest="{{ dstdir + '.' + 'localhost' }}" mode=pull
      register: result
    - debug: var=result
    - fail: 
      when: "who.stdout + '@127.0.0.2:/tmp/foosrc /tmp/foodst.localhost' not in result.cmd"
    - shell: if [ ! -d "{{ dstdir + '.' + inventory_hostname }}" ]; then exit 1; fi


    # /tmp/foosrc jtanner@127.0.0.2:/tmp/foodst.ahost
    - name: local connection push
      local_action: synchronize src="{{ srcdir }}" dest="{{ dstdir + '.' + inventory_hostname }}"
      register: result
    - debug: var=result
    - fail:
      when: "' /tmp/foosrc ' + who.stdout + '@127.0.0.2:/tmp/foodst.' + inventory_hostname not in result.cmd"

    # jtanner@127.0.0.2:/tmp/foosrc /tmp/foodst.ahost
    - name: local connection pull
      local_action: synchronize src="{{ srcdir }}" dest="{{ dstdir + '.' + inventory_hostname }}" mode=pull
      register: result
    - debug: var=result
    - fail:
      when: "who.stdout + '@127.0.0.2:/tmp/foosrc /tmp/foodst.' + inventory_hostname not in result.cmd"


# HOW DO WE VERIFY ANSIBLE SSH'ED TO THE REMOTE HOST TO CALL RSYNC? CAN IT?
- hosts: bhost
  gather_facts: False
  vars:
    - srcdir: /tmp/foosrc
    - dstdir: /tmp/foodst
  tasks:
    - shell: whoami
      register: who

    - name: verify dest_port works as a parameter
      synchronize: src="{{ srcdir }}" dest="{{ dstdir + '.' + inventory_hostname }}" dest_port=2222
      register: result
    - debug: var=result
    - fail:
      when: "'-o Port=2222' not in result.cmd"


- name: tests against port 2222
  hosts: chost
  gather_facts: False
  vars:
    - srcdir: /tmp/foosrc
    - dstdir: /tmp/foodst
  tasks:
    - shell: whoami
      register: who

    - name: make sure the remote port is set to 2222 by inventory
      synchronize: src="{{ srcdir }}" dest="{{ dstdir + '.' + inventory_hostname }}"
      register: result
    - debug: var=result
    - fail:
      when: "'-o Port=2222' not in result.cmd"


#####################################

- name: cleanup environment
  hosts: localhost
  gather_facts: False
  user: root
  tasks:
    - name: stop sshd on port 2222
      shell: lsof -i :2222 | egrep ^sshd | awk '{print $2}' | head -n1 | xargs kill

